### ISSUE TITLE
Installation Instructions do not work

### ISSUE THREAD

**Issue by pgorbas** [MvcControlsToolkit/Home#1]
Section 2:  Instructions say to "Install the following Bower packages..."  it should really detail HOW to do so, or at least provide a link.

Section 3: Instructions say "install the following npm packages...cldr-data, globalize, mvcct-templates"  NuGet package manager can not find npm packages with these exact names - they must be wrong?

**Comment by frankabbruzzese** [comment]
@pgorbas Asp.net core projects use Nuget for server side packages but use other package management stuff fo JavaScript. Namely Bower and npm. 

In order to install Bower Packages.

In the solution exploree there is a "Dpendencies" node. Open it, you should see a Bower folder. Right click on it and select "opnen Bower.json". A json file should open. There you may add the Bower packages to install. When you save the file installation will take place automatically. See [here](https://webtooling.visualstudio.com/package-managers/bower/) to have an idea of how to insert the package names.

In order to install Bower Packages.

In the solution explorer there is a "Dpendencies" node.  If you dont see an NPM folder do the following:
right click on the project node (project not solution!) and selecct "add new item", then select ".Net Core" and then "client side". Here select "package.json" file type. DO NOT change name to the file, but accept the suggested "package.json".
Now an npm folde should appear under "Dependencies". Right click on it ad select "open package.json".
Once the file is opened add the packages to install as with Bower. Pay attention cldr-data must be installed before all others, so add it and click save, to start installation. After completion (it may take some minutes since it download several language packages) add all other packages.

This week we will publish a dedicated documentation web site,
